#ifndef _pins_h
#define _pins_h

#include <Arduino.h>

// ANALOG INPUTS
#define POTIENTIOMETER_PIN PA0
#define SOLAR_VOLATGE_SENSE_PIN PA1
#define BATTTERY_1_VOLTAGE_SENSE_PIN PA2
#define BATTTERY_2_VOLTAGE_SENSE_PIN PA3
#define DC_DISCHARGE_CURRENT_SENSE_PIN PA4
#define SENS_ENABLE PB13

// CHARGER CONTROL
#define BAT1_CHGR_ENABLE PA7
#define BAT1_CHGR_STATUS PA5
#define BAT1_CHGR_VOLTAGE_SWITCH PA6
#define BAT2_CHGR_ENABLE PB2
#define BAT2_CHGR_STATUS PB0
#define BAT2_CHGR_VOLTAGE_SWITCH PB1

// OUTPUT CONTROL
#define EN_BOOST PB14
#define PG_BOOST PA8
#define EN_OUTPUT PB15

// LIGHT BAR
#define LIGHT_BAR1_ENABLE PD3
#define LIGHT_BAR2_ENABLE PB12
#define LIGHT_BAR1 PC7
#define LIGHT_BAR2 PC6

// FRONT PANEL
#define WS2812_PIN PD0
#define FRONT_PANEL_BUTTON PD1
#define BUZZER PD2

// DIP SWITCHES
#define DIP_SWITCH_1 PB3
#define DIP_SWITCH_2 PB4
#define DIP_SWITCH_3 PB5

// RF INPUT
#define RF_IN1 PB9
#define RF_IN2 PB8

// MOTOR CONTROL
#define WISCH1_PIN PB6
#define WISCH2_PIN PB7
#define MOTOR_OPTO_1 PA12
#define MOTOR_OPTO_2 PA11

// KEY SWICHES
#define KEY_SWITCH_1 PC13
#define KEY_SWITCH_2 PC14

// DEBUG
#define DEBUG_LED PA15
#define DEBUG_TX PA9
#define DEBUG_RX PA10

// EXPANSION PORT
#define EXPANSION_TX PB10
#define EXPANSION_RX PB11
#define EXPANSION_GPIO PC15

#endif // _pins_h